name: Notify Slack on Branch Deletion

on:
  delete:
    branches:
      - '**'

jobs:
  slack-notification:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        uses: archive/github-actions-slack@v2.7.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_ACCESS_TOKEN }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          slack-text: |
            The ${{ github.event.ref }} branch was deleted by ${{ github.actor }}
