name: Notify Slack on Push

on:
  push:
    branches:
      - '*'

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get commit message
        id: commit
        run: echo "::set-output name=message::$(git log -1 --pretty=format:'%s')"

      - name: Send Slack Message
        uses: archive/github-actions-slack@v2.7.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_ACCESS_TOKEN }}
          slack-channel: ${{ vars.SLACK_CHANNEL }}
          slack-text: |
            Changes pushed to the repository by ${{ github.actor }}:
            ```
            ${{ steps.commit.outputs.message }}
            ```
